### ISSUE TITLE
Cannot set the number of cards

### ISSUE THREAD

**Issue by lpinter** [fyyyyy/tabloro#12]
I love the idea to have a place where I can play with my friends without the computer enforcing rules and telling us what to do.  We want to play Robber's Rummy, and there is no online place to play it.

I have created a spriteset and used it as the cards of the Robbers_Rummy_box. When I want to set the number of cards, I can only set it for piece #1, the rest do not have form fields to enter numbers. 

![tabloro com - cannot set number of cards](https://user-images.githubusercontent.com/30354422/79702184-d2493480-8257-11ea-8337-4823ab5a8b66.png)

**Comment by fyyyyy** [comment]
do you have a link to the piece?

**Comment by fyyyyy** [comment]
Seems you did something wrong during piece setup.
Try this one
piece:
http://www.tabloro.com/pieces/5e9d515a0161e2001456e11c
box:
http://www.tabloro.com/boxes/5e9d51b00161e2001456e11e

**Comment by lpinter** [comment]
I know why my piece did not work. I selected "Is stash" when I created the
piece. That disabled the fields in the form when I wanted to set the number
of cards.
![2020-04-22_22-37-00](https://user-images.githubusercontent.com/30354422/80136779-0cb41980-8557-11ea-976c-7ce908f7558d.jpg)

This is an amazing site, these days during the lockdown, I know other
people are also looking for platforms to play with their families and
friends.
I would recommend some improvements:

- When I click a card on the pile and take it to my hand, if I have more
than it fits on the screen (13), the new card hides under the rest. It
would be nice to lay down all cards in my hand on the bottom of the table
to see all. Maybe, to scroll the cards in my hand independently of the
table while the table stays in place.
![2020-04-23_0-04-20](https://user-images.githubusercontent.com/30354422/80149271-3b3bef80-856b-11ea-9242-353b2e9f0029.jpg)

- If I click a card in my hand, the card flips and slides under the rest
![2020-04-23_0-14-49](https://user-images.githubusercontent.com/30354422/80149294-43942a80-856b-11ea-8612-a9cc2941f30a.jpg)

- If I move the cards in my hand to reorganize them, the card flips, and
makes it visible for everyone (maybe it should be visible only when I move
it up from the bottom row)
- It would be great if the Z order of the cars would be the same for
everyone, so I could put cards close to each other and everyone would see
them in the same order
![2020-04-23_0-03-35](https://user-images.githubusercontent.com/30354422/80149313-4bec6580-856b-11ea-9927-4e85fb5077ed.jpg)
![2020-04-23_0-05-50](https://user-images.githubusercontent.com/30354422/80149315-4ee75600-856b-11ea-9179-6d618a03ba3d.jpg)

I have already forked the code, I will take a look to see if I can figure
out ways to improve the site and send you PRs. I would love to play with it
with my friends.
Thank you so much for starting this awesome project.

Laszlo
